# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@ampproject/remapping-2.3.0" = {
      name = "_at_ampproject_slash_remapping";
      packageName = "@ampproject/remapping";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@ampproject/remapping/-/remapping-2.3.0.tgz";
        sha512 = "30iZtAPgz+LTIYoeivqYo853f02jBYSd5uGnGpkFV0M3xOt9aN73erkgYAmZU43x4VfqcnLxW9Kpg3R5LC4YYw==";
      };
    };
    "@jridgewell/gen-mapping-0.3.8" = {
      name = "_at_jridgewell_slash_gen-mapping";
      packageName = "@jridgewell/gen-mapping";
      version = "0.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/gen-mapping/-/gen-mapping-0.3.8.tgz";
        sha512 = "imAbBGkb+ebQyxKgzv5Hu2nmROxoDOXHh80evxdoXNOrvAnVx7zimzc1Oo5h9RlfV4vPXaE2iM5pOFbvOCClWA==";
      };
    };
    "@jridgewell/resolve-uri-3.1.2" = {
      name = "_at_jridgewell_slash_resolve-uri";
      packageName = "@jridgewell/resolve-uri";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/resolve-uri/-/resolve-uri-3.1.2.tgz";
        sha512 = "bRISgCIjP20/tbWSPWMEi54QVPRZExkuD9lJL+UIxUKtwVJA8wW1Trb1jMs1RFXo1CBTNZ/5hpC9QvmKWdopKw==";
      };
    };
    "@jridgewell/set-array-1.2.1" = {
      name = "_at_jridgewell_slash_set-array";
      packageName = "@jridgewell/set-array";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/set-array/-/set-array-1.2.1.tgz";
        sha512 = "R8gLRTZeyp03ymzP/6Lil/28tGeGEzhx1q2k703KGWRAI1VdvPIXdG70VJc2pAMw3NA6JKL5hhFu1sJX0Mnn/A==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.0" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.0.tgz";
        sha512 = "gv3ZRaISU3fjPAgNsriBRqGWQL6quFx04YMPW/zD8XMLsU32mhCCbfbO6KZFLjvYpCZ8zyDEgqsgf+PwPaM7GQ==";
      };
    };
    "@jridgewell/trace-mapping-0.3.25" = {
      name = "_at_jridgewell_slash_trace-mapping";
      packageName = "@jridgewell/trace-mapping";
      version = "0.3.25";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/trace-mapping/-/trace-mapping-0.3.25.tgz";
        sha512 = "vNk6aEwybGtawWmy/PzwnGDOjCkLWSD2wqvjGGAgOAwCGWySYXfYoxt00IJkTF+8Lb57DwOb3Aa0o9CApepiYQ==";
      };
    };
    "@sveltejs/acorn-typescript-1.0.5" = {
      name = "_at_sveltejs_slash_acorn-typescript";
      packageName = "@sveltejs/acorn-typescript";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@sveltejs/acorn-typescript/-/acorn-typescript-1.0.5.tgz";
        sha512 = "IwQk4yfwLdibDlrXVE04jTZYlLnwsTT2PIOQQGNLWfjavGifnk1JD1LcZjZaBTRcxZu2FfPfNLOE04DSu9lqtQ==";
      };
    };
    "@types/estree-1.0.7" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.7.tgz";
        sha512 = "w28IoSUCJpidD/TGviZwwMJckNESJZXFu7NBZ5YJ4mEUnNraUn9Pm8HSZm/jDF1pDWYKspWE7oVphigUPRakIQ==";
      };
    };
    "acorn-8.14.1" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.14.1.tgz";
        sha512 = "OvQ/2pUDKmgfCg++xsTX1wGxfTaszcHVcTctW4UJB4hibJx2HXxxO5UmVgyjMa+ZDsiaf5wWLXYpRWMmBI0QHg==";
      };
    };
    "aria-query-5.3.2" = {
      name = "aria-query";
      packageName = "aria-query";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/aria-query/-/aria-query-5.3.2.tgz";
        sha512 = "COROpnaoap1E2F000S62r6A60uHZnmlvomhfyT2DlTcrY1OrBKn2UhH7qn5wTC9zMvD0AY7csdPSNwKP+7WiQw==";
      };
    };
    "axobject-query-4.1.0" = {
      name = "axobject-query";
      packageName = "axobject-query";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/axobject-query/-/axobject-query-4.1.0.tgz";
        sha512 = "qIj0G9wZbMGNLjLmg1PT6v2mE9AH2zlnADJD/2tC6E00hgmhUOfEB6greHPAfLRSufHqROIUTkw6E+M3lH0PTQ==";
      };
    };
    "clsx-2.1.1" = {
      name = "clsx";
      packageName = "clsx";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/clsx/-/clsx-2.1.1.tgz";
        sha512 = "eYm0QWBtUrBWZWG0d386OGAw16Z995PiOVo2B7bjWSbHedGl5e0ZWaq65kOGgUSNesEIDkB9ISbTg/JK9dhCZA==";
      };
    };
    "dedent-js-1.0.1" = {
      name = "dedent-js";
      packageName = "dedent-js";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dedent-js/-/dedent-js-1.0.1.tgz";
        sha512 = "OUepMozQULMLUmhxS95Vudo0jb0UchLimi3+pQ2plj61Fcy8axbP9hbiD4Sz6DPqn6XG3kfmziVfQ1rSys5AJQ==";
      };
    };
    "esm-env-1.2.2" = {
      name = "esm-env";
      packageName = "esm-env";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esm-env/-/esm-env-1.2.2.tgz";
        sha512 = "Epxrv+Nr/CaL4ZcFGPJIYLWFom+YeV1DqMLHJoEd9SYRxNbaFruBwfEX/kkHUJf55j2+TUbmDcmuilbP1TmXHA==";
      };
    };
    "esrap-1.4.6" = {
      name = "esrap";
      packageName = "esrap";
      version = "1.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/esrap/-/esrap-1.4.6.tgz";
        sha512 = "F/D2mADJ9SHY3IwksD4DAXjTt7qt7GWUf3/8RhCNWmC/67tyb55dpimHmy7EplakFaflV0R/PC+fdSPqrRHAQw==";
      };
    };
    "is-reference-3.0.3" = {
      name = "is-reference";
      packageName = "is-reference";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-reference/-/is-reference-3.0.3.tgz";
        sha512 = "ixkJoqQvAP88E6wLydLGGqCJsrFUnqoH6HnaczB8XmDH1oaWU+xxdptvikTgaEhtZ53Ky6YXiBuUI2WXLMCwjw==";
      };
    };
    "locate-character-3.0.0" = {
      name = "locate-character";
      packageName = "locate-character";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-character/-/locate-character-3.0.0.tgz";
        sha512 = "SW13ws7BjaeJ6p7Q6CO2nchbYEc3X3J6WrmTTDto7yMPqVSZTUyY5Tjbid+Ab8gLnATtygYtiDIJGQRRn2ZOiA==";
      };
    };
    "lower-case-2.0.2" = {
      name = "lower-case";
      packageName = "lower-case";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lower-case/-/lower-case-2.0.2.tgz";
        sha512 = "7fm3l3NAF9WfN6W3JOmf5drwpVqX78JtoGJ3A6W0a6ZnldM41w2fV5D490psKFTpMds8TJse/eHLFFsNHHjHgg==";
      };
    };
    "magic-string-0.30.17" = {
      name = "magic-string";
      packageName = "magic-string";
      version = "0.30.17";
      src = fetchurl {
        url = "https://registry.npmjs.org/magic-string/-/magic-string-0.30.17.tgz";
        sha512 = "sNPKHvyjVf7gyjwS4xGTaW/mCnF8wnjtifKBEhxfZ7E/S8tQ0rssrwGNn6q8JH/ohItJfSQp9mBtQYuTlH5QnA==";
      };
    };
    "no-case-3.0.4" = {
      name = "no-case";
      packageName = "no-case";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/no-case/-/no-case-3.0.4.tgz";
        sha512 = "fgAN3jGAh+RoxUGZHTSOLJIqUc2wmoBwGR4tbpNAKmmovFoWq0OdRkb0VkldReO2a2iBT/OEulG9XSUc10r3zg==";
      };
    };
    "pascal-case-3.1.2" = {
      name = "pascal-case";
      packageName = "pascal-case";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pascal-case/-/pascal-case-3.1.2.tgz";
        sha512 = "uWlGT3YSnK9x3BQJaOdcZwrnV6hPpd8jFH1/ucpiLRPh/2zCVJKS19E4GvYHvaCcACn3foXZ0cLB9Wrx1KGe5g==";
      };
    };
    "svelte-5.31.1" = {
      name = "svelte";
      packageName = "svelte";
      version = "5.31.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte/-/svelte-5.31.1.tgz";
        sha512 = "09fup3U7NQobUCUJnLhed6pxG6MzUS8rPsALB5Jr8m8u3pVKITs0ejYiKS/wsVjfkXHvKc2g260KA8o7dWypHA==";
      };
    };
    "svelte2tsx-0.7.39" = {
      name = "svelte2tsx";
      packageName = "svelte2tsx";
      version = "0.7.39";
      src = fetchurl {
        url = "https://registry.npmjs.org/svelte2tsx/-/svelte2tsx-0.7.39.tgz";
        sha512 = "NX8a7eSqF1hr6WKArvXr7TV7DeE+y0kDFD7L5JP7TWqlwFidzGKaG415p992MHREiiEWOv2xIWXJ+mlONofs0A==";
      };
    };
    "tslib-2.8.1" = {
      name = "tslib";
      packageName = "tslib";
      version = "2.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
        sha512 = "oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
      };
    };
    "typescript-5.8.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.8.3.tgz";
        sha512 = "p1diW6TqL9L07nNxvRMM7hMMw4c5XOo/1ibL4aAIGmSAt9slTE1Xgw5KWuof2uTOvCg9BY7ZRi+GaF+7sfgPeQ==";
      };
    };
    "typescript-svelte-plugin-0.3.47" = {
      name = "typescript-svelte-plugin";
      packageName = "typescript-svelte-plugin";
      version = "0.3.47";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-svelte-plugin/-/typescript-svelte-plugin-0.3.47.tgz";
        sha512 = "q7NpMvWokP8n0MfAhB375K3PT+1iYuPC/wFYxOTWMiraCkA81GDA8X/b2DfdiuESfDTJ1VANUR2PqdE8pEqXxg==";
      };
    };
    "zimmerframe-1.1.2" = {
      name = "zimmerframe";
      packageName = "zimmerframe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/zimmerframe/-/zimmerframe-1.1.2.tgz";
        sha512 = "rAbqEGa8ovJy4pyBxZM70hg4pE6gDgaQ0Sl9M3enG3I0d6H4XSAM3GeNGLKnsBpuijUow064sf7ww1nutC5/3w==";
      };
    };
  };
  args = {
    name = "typescript-svelte-plugin";
    packageName = "typescript-svelte-plugin";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@ampproject/remapping-2.3.0"
      sources."@jridgewell/gen-mapping-0.3.8"
      sources."@jridgewell/resolve-uri-3.1.2"
      sources."@jridgewell/set-array-1.2.1"
      sources."@jridgewell/sourcemap-codec-1.5.0"
      sources."@jridgewell/trace-mapping-0.3.25"
      sources."@sveltejs/acorn-typescript-1.0.5"
      sources."@types/estree-1.0.7"
      sources."acorn-8.14.1"
      sources."aria-query-5.3.2"
      sources."axobject-query-4.1.0"
      sources."clsx-2.1.1"
      sources."dedent-js-1.0.1"
      sources."esm-env-1.2.2"
      sources."esrap-1.4.6"
      sources."is-reference-3.0.3"
      sources."locate-character-3.0.0"
      sources."lower-case-2.0.2"
      sources."magic-string-0.30.17"
      sources."no-case-3.0.4"
      sources."pascal-case-3.1.2"
      sources."svelte-5.31.1"
      sources."svelte2tsx-0.7.39"
      sources."tslib-2.8.1"
      sources."typescript-5.8.3"
      sources."typescript-svelte-plugin-0.3.47"
      sources."zimmerframe-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
